name: 🌟 Feature Request
description: Suggest a feature idea for this project
title: '[feat] <title>'
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing request for this?
      description: Please search to see if an feature request (issue) already exists for the bug you encountered.
      options:
        - label: I have searched the existing feature requests
          required: true
  - type: textarea
    attributes:
      label: Is the feature request related to a problem?
      description: A concise description of the issue. E.g I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Is the feature request related to a existing bug/RFC?
      description: If so, please put the PR/Issue number below.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: What does the feature request look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the definition of done?
      description: What are it's subtasks? How do we know the feature request is fulfilled?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any solutions considered?
      description: |
        Did you consider alternative solutions or features? Do you have a proposed solution for the feature request?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you able to assist to bring the feature to reality?
      options:
        - No
        - Yes, I can
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
